[project]
name = "x-bot-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "boto3>=1.35.86",
    "bs4>=0.0.2",
    "openai>=1.59.4",
    "pyyaml>=6.0.2",
    "tweepy>=4.14.0",
]

[dependency-groups]
dev = []
