secret_name: "prod/demo-secrets"

follow:
  post_search_query: "#猫がいる暮らし OR #ペルシャ猫 OR #メインクーン OR #猫好きさんと繋がりたい"
  max_follow_count: 5
  filter:
    min_followers: 50
    allow_protected: false

post:
  source_account_name: livedoornews
  max_lookback_hours: 1
  post_search_query: ""
  post_instruction_prompt: |-
    ネットニュース記事のタイトルと本文を入力します。
    その記事に対する反応ツイートを作成してください。
    記事の要約を本文に含めず、反応・感想だけをツイートしてください。
    出力はツイート本文のみで、ハッシュタグは使用せず、50文字以内で作成してください。
  post_style_examples:
    - |-
      [記事]
      タイトル: 【高級ラーメン】あれもこれも全部サーモン！ 材料"鮭だけ"でラーメンは作れるか？
      本文: 麺、スープ、具材を全て鮭だけで調理することに挑戦。スープの味付けにも鮭の魚醤を使ったほか、鮭を蒸して作ったなるともトッピング。材料にかかった値段は5089円となった。

      [ツイート例1]
      すごい！
      めっちゃ贅沢！
      ぜひ北海道で採れたてで食べたい

      [ツイート例2]
      シャケラーメン！！！

    - |-
      [記事]
      タイトル: 【団地育ち】しろくま「ピース」、飼育員との命を巡る25年の物語 NHKで4日21時から放送
      本文: ピースは、飼育員が献身的に支えて人工哺育されたホッキョクグマ。現在は老いの問題に直面。血液検査も拒むようになったピースに向き合う姿を1年かけて取材したという。
  
      [ツイート例1]
      写真のピースがめちゃめちゃかわいい♡
      NHKで21時から放送ですね。

      [ツイート例2]
      25年間、ほぼ毎日ピースを見続けた飼育員、高市さん。映像を見たら、高市さんが若者から高齢化していく姿に年月を感じて涙した。ピース、長生きして欲しいね。
      いつかは死ぬのはわかってるけど、後悔だけはしたくないと話す高市さんに、高齢猫と暮らす私も深く共感した。
